### PR TITLE
#82 - Adds PHP 7.3 requirements to circle and build config

### PR DESCRIPTION
**Pull request by aprice42**
- Issue #82

### CODE REVIEW

**Comment by aprice42** [comment]
@mariacha I took the steps outlined in the ticket and circle build was good. Seems good to me, unless I missed something?

**Comment by mariacha** [comment]
There's one more file you need to update: https://github.com/thinkshout/drupal-project/blob/8.x-pantheon/pantheon.yml#L3 otherwise yay!

**Comment by aprice42** [comment]
Oops, sorry I missed that. Updated now!

**Comment by mariacha** [comment]
Love it!

**Pull request merged**
