### PR TITLE
Rename production branch

### PR DESCRIPTION
**Pull request by unclegcb**
Not much here: and ~~this shouldn't be merged until this is merged:~~
https://github.com/thinkshout/robo-drupal/pull/65 (merged)

And a release is rolled that matches the version here (3.0.0) for robo drupal. (done)

This also updates instructions to avoid ending up with a "master" branch on new repositories, and set up develop while we are at it. (not necessary anymore, removed, because Github sets a better default)

### CODE REVIEW

**Comment by unclegcb** [comment]
@mariacha failed tests here don't seem related to what's in this PR. Cool to merge?

**Comment by mariacha** [comment]
I'd prefer not to since this will mean tests fail in the 8.x-pantheon branch from now on and who knows how long that will be the case. It looks like it's just a patch that's no longer needed, right?

**Comment by unclegcb** [comment]
That seems fair! Fixed, I think.

**Comment by unclegcb** [comment]
Ok, still an error but it's not our fault! a stable release of a module is just broken: https://www.drupal.org/project/config_suite/issues/3189614#comment-13947443

**Comment by mariacha** [comment]
Great!

**Pull request merged**
